// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3z8E35Dwy30fEb3CdzhNCfgrvmIFX9o',
    appId: '1:693050067524:web:fd1d34444c05dcb01b0a11',
    messagingSenderId: '693050067524',
    projectId: 'investtrack-2b362',
    authDomain: 'investtrack-2b362.firebaseapp.com',
    storageBucket: 'investtrack-2b362.firebasestorage.app',
    measurementId: 'G-D997JXKMHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfxzAtf48_hVUUJ-p9cCVA5QnAR6jFxwc',
    appId: '1:693050067524:android:a82ad865717a57691b0a11',
    messagingSenderId: '693050067524',
    projectId: 'investtrack-2b362',
    storageBucket: 'investtrack-2b362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsllUWXhuNMtKpmMg13Xn9IddvXnhzjY',
    appId: '1:693050067524:ios:a3b51971742b411f1b0a11',
    messagingSenderId: '693050067524',
    projectId: 'investtrack-2b362',
    storageBucket: 'investtrack-2b362.firebasestorage.app',
    iosBundleId: 'com.example.investtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsllUWXhuNMtKpmMg13Xn9IddvXnhzjY',
    appId: '1:693050067524:ios:a3b51971742b411f1b0a11',
    messagingSenderId: '693050067524',
    projectId: 'investtrack-2b362',
    storageBucket: 'investtrack-2b362.firebasestorage.app',
    iosBundleId: 'com.example.investtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn3z8E35Dwy30fEb3CdzhNCfgrvmIFX9o',
    appId: '1:693050067524:web:4be7964ce532ccf71b0a11',
    messagingSenderId: '693050067524',
    projectId: 'investtrack-2b362',
    authDomain: 'investtrack-2b362.firebaseapp.com',
    storageBucket: 'investtrack-2b362.firebasestorage.app',
    measurementId: 'G-SL0654ZWQG',
  );
}
